---
name: blue9
description: OS 9 in an atomic fashion

base-image: ghcr.io/winblues/vauxite
image-version: 42

modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: rpm-ostree
    install:
      - audacious
      - plymouth-plugin-script

  - type: script
    scripts:
      #- 00-image-info.sh
      - 00-image-info.sh
      - 01-main.sh
      - 10-platinum9.sh
      - 11-b00merang.sh
      - 22-fonts.sh
      - 90-finalize.sh

  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      install:
        - org.mozilla.firefox
        - com.tomjwatson.Emote
        - org.geany.Geany
        - org.libreoffice.LibreOffice

    user: {} # Also add Flathub user repo, but no user packages

  # Regenerate initramfs because of plymouth
  - type: initramfs

#  - type: bling
#    install:
#      - 1password

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

